FROM debian:12

COPY requirements.txt /

RUN apt update \
    && apt install -y openjdk-17-jdk \
    && apt install -y python3-pip \
    && apt install -y git \
    && apt install -y python3.11-venv \
    && python3 -m venv .venv \
    && .venv/bin/pip3 install --no-cache-dir -r /requirements.txt \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*